---
kind: pipeline
type: exec
name: Build all hosts

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: Show flake info
  commands:
  - nix --experimental-features "nix-command flakes" flake show
  - nix --experimental-features "nix-command flakes" flake metadata
  - nix --experimental-features "nix-command flakes" flake check

- name: Run flake checks
  commands:
  - nix --experimental-features "nix-command flakes" flake check --show-trace

- name: Build quinjet
  commands:
  - nix build -v '.#nixosConfigurations.quinjet.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"

- name: Build the-hub
  commands:
  - nix build -v '.#nixosConfigurations.the-hub.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"

- name: Build the-bus
  commands:
  - nix build -v '.#nixosConfigurations.the-bus.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"

- name: Build water-on-fire
  commands:
  - nix build -v '.#nixosConfigurations.water-on-fire.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"

trigger:
  branch:
  - main
  event:
  - push
  - pull_request
  - cron

---
kind: pipeline
type: exec
name: build flake update

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: flake update
  commands:
  - nix --experimental-features "nix-command flakes" flake update --inputs-from nixpkgs
  
- name: Show git diff
  commands:
  - git diff

- name: Show flake info
  commands:
  - nix --experimental-features "nix-command flakes" flake show
  - nix --experimental-features "nix-command flakes" flake metadata
  - nix --experimental-features "nix-command flakes" flake check

- name: Run flake checks
  commands:
  - nix --experimental-features "nix-command flakes" flake check --show-trace

- name: Build quinjet
  commands:
  - nix build -v '.#nixosConfigurations.quinjet.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"

- name: Build the-hub
  commands:
  - nix build -v '.#nixosConfigurations.the-hub.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"

- name: Build the-bus
  commands:
  - nix build -v '.#nixosConfigurations.the-bus.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"

- name: Build water-on-fire
  commands:
  - nix build -v '.#nixosConfigurations.water-on-fire.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"

trigger:
  branch:
  - main
  - overlay
  event:
  - push
  - pull_request
  - cron

---
kind: pipeline
name: push flake update
type: docker

steps:
- name: Update flake.lock
  image: nixpkgs/nix-flakes
  commands:
  - nix flake update --inputs-from nixpkgs
  - nix flake show
  - nix flake metadata
  - nix flake check
  - nix flake check --show-trace
  environment:
    NIX_PATH: nixpkgs=channel:nixos-unstable

- name: Push updated flake.lock
  image: appleboy/drone-git-push
  settings:
    branch: update-flake
    remote: git@github.com:MayNiklas/nixos.git
    force: true
    commit: true
    force: true
    commit_message: "❄️ Update flake.lock"
    ssh_key:
      from_secret: deploy_key

- name: notify on failure
  image: drillster/drone-email
  settings:
    username: apikey
    from:
      from_secret: email_from
    host:
      from_secret: email_host
    password:
      from_secret: email_password
  when:
    status:
    - failure

trigger:
  branch:
  - main
  event:
  - push
  - cron
