---
kind: pipeline
type: exec
name: Build all hosts

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: Show flake info
  commands:
  - nix --experimental-features "nix-command flakes" flake show
  - nix --experimental-features "nix-command flakes" flake metadata
  - nix --experimental-features "nix-command flakes" flake check

- name: Run flake checks
  commands:
  - nix --experimental-features "nix-command flakes" flake check --show-trace

- name: Build aida
  commands:
  - nix build -v '.#nixosConfigurations.aida.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"

- name: Build kora
  commands:
  - nix build -v '.#nixosConfigurations.kora.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"

- name: Build quinjet
  commands:
  - nix build -v '.#nixosConfigurations.quinjet.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"

- name: Build the-hub
  commands:
  - nix build -v '.#nixosConfigurations.the-hub.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"

- name: Build the-bus
  commands:
  - nix build -v '.#nixosConfigurations.the-bus.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"

- name: Build water-on-fire
  commands:
  - nix build -v '.#nixosConfigurations.water-on-fire.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"

trigger:
  branch:
  - main
  event:
  - push
  - pull_request
  - cron

---
kind: pipeline
type: exec
name: build flake update & push into update-flake

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: flake update
  commands:
  - nix --experimental-features "nix-command flakes" flake update --inputs-from nixpkgs
  
- name: Show git diff
  commands:
  - git diff

- name: Show flake info
  commands:
  - nix --experimental-features "nix-command flakes" flake show
  - nix --experimental-features "nix-command flakes" flake metadata
  - nix --experimental-features "nix-command flakes" flake check

- name: Run flake checks
  commands:
  - nix --experimental-features "nix-command flakes" flake check --show-trace

- name: Build aida
  commands:
  - nix build -v '.#nixosConfigurations.aida.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"

- name: Build kora
  commands:
  - nix build -v '.#nixosConfigurations.kora.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"

- name: Build quinjet
  commands:
  - nix build -v '.#nixosConfigurations.quinjet.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"

- name: Build the-hub
  commands:
  - nix build -v '.#nixosConfigurations.the-hub.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"

- name: Build the-bus
  commands:
  - nix build -v '.#nixosConfigurations.the-bus.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"

- name: Build water-on-fire
  commands:
  - nix build -v '.#nixosConfigurations.water-on-fire.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"

- name: push updated flake
  environment:
    SSH_KEY:
      from_secret: id_rsa
  commands:
  - mkdir ~/.ssh
  - echo "$SSH_KEY" >> ~/.ssh/id_rsa
  - chmod 400 ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
  - ssh-keyscan github.com >> ~/.ssh/known_hosts
  - git config --global user.name "MayNiklas"
  - git config --global user.email info@niklas-steffen.de
  - git remote set-url origin git@github.com:MayNiklas/nixos.git
  - git checkout -B update-flake
  - git add flake.lock
  - git commit -m "❄️ Update flake.lock"
  - git push --set-upstream origin update-flake --force

trigger:
  branch:
  - main
  - optimize-droneci
  event:
  - push
  - cron

---
kind: secret
name: id_rsa
data: u26mPv6JS/x9OspRw4fUzvi1SBHYY9a8EB/pwVvCbF4EPH0C79rIJpm81iDmKM5hSCZHEES4A107QA4waZwYao2bAh+frCnrNs2swNtKlo7HXbaYwVZ0dIYuSjAnX9dBBKjo/DCcN7MQ9BHS/iqFVr39yVFS+9CwHAezx/fpIavv9LiyeMDiGWczuKiVvmyQWOpvkD2YTMixAZOneDmlRMCAwlTI0GpAxK3rbYiL2TM8NQJYxNjNvHrT/ByFr0ha5tKSUg5hR7DrAsP29bdl5po5wqpkDWsGNYNhztz8ha6cNmKYbRDbsLZA7ESU/zsyRRzYyEeE3BHr04ffymUT31ZaAnFsCLhE89WMzelq1xv1/oZWgzxuoOrH+RP+RHWqoTMrDl6eT0+ioOXqXtXKPjdoKCz19FFuCffivOcpRdJzkCLZczAFCSTT0OVi8GXuWAlIRI8MjbP5lzUvJrkQYw5eqWHZu1JA3I0jX4QtrInUKK9g6H3CRNEEvxIO5aRtxy+fwRz70ZWpyGx7N2iPVCq6NAXpmUITFZO2qQ5KxtUn1P6flJeR7Mg+nPRnVVQGTV+t13RijRlqSAp6QQiULFfIc/yC8QFg3IKKE8rDTX4l9+nk/s0RYdT1RI9XGGe12KmzWTR5LNpPTKVNzzDkSLvKGywztazB+ExAhM+UGq0bHesYC3IbqpYewms2/GGjRmQOEZqRP4lTJJSoRNV7C1EkWOn8ngTtr8pNDgrKOKSOHvIcmT84Ru8ltoAsByJIfMPlFFWGTIp9ITNVm2scdK4MxTj3TyNq7kqf0tVABHLXbEt9zgKmSFGWCAaKRU7q4FbYCeYIovUjGIgdmRXqYoqjT0a7a3Fyz0iqKiJIrel/h4alEcP6F6Qv1WSPsYB/TleAQOorx6MGrShEjbHmoDFQg8yvGhZMZD3IBqnVy8Y5p7QmpFJeescRc4facwIcFvjfY2/sDTY3KnAbdw06PMzT15e3coDwwCTSwY5l9rxRkwiQU61OIrI7rWPRsyqrOc9g+aA5PPhxEKQ2VJ6eWQhpUlJ6R36irUuoG905Yty1lPOpS7FWZ4yN2gkZXpz3GaEuilF5oRB3plMQfgs11aL4z68bLHKnsq5fay74hvidkKo8kvDuiGHDd2m1i+BcAWjtgOmWgTcfsoGpp6+D3pZ7BF6fufgiBu+gSj3akMEXgXDeT7NxLd65IMvC3SghMi3yFDoshz9T/1obj+gyrcHwqua1/EtqWc6F27xGzV7weEerc4cHmcboIfhB+qtDWlkItiaOo5HY58wag9BCFTMYrhrMo57b/Ihxr9/w7NKOCHtvlEcR7PkmQV85KXSen28/PyYAHNmX0neqOGkv6RicpdFTsGyh+LQ2d5mnRC2LeN17vENhbG3n/G9AT3iJvjv/yc26pJoEZUxmZe45TD5vE80SFqq3lss0slhLGxQZsVkwGX79w9P5C6iSN5cztgnw+qRJoX6kQ1uZyVohBQxbd6okeVJTiG/m74qPAYL1EYqtocyHUQl8+RELud5KIKmmQh/skmU2Wus7XZGQQjFqYSk3QTAsHgfAP+AqiyE7j37AKwG7FUNF7aPa1/Pi/dg9AuYGL4aJnRKRFuMW+ExacZWll0F8E1uRb3VSxzyIOQde2Lo12xXQ27nGuzimuhABrXSg4pFcB4jxcsaFK0aHnUgd8xeYrA/Lhx//Nc4jmUYakUXm6hlVJR5CNKqoMMndoEFj+zNzG4W8BgvmAM0g1+77hMgQhLIXYk7C5PJ6+DzrxUYi78Q7lftlGXEwOBHu1noq2BDpFtTcdRw25tN0h3CgKQ4suEG9cwr7DrrRGo/hSYAIbt3roDSBrTmDYMZ6xiXNHi/D44SHUoo86t8pP3Ks4VVXUGCC2jJ3EB7MG6K/H5yxKbJc/U/oO3PXrj26gzZ2bCGbdxL8yDSN+HxuWl32XB1OSyWIX8ewPWN2b4oRTrzBVOMLWpO+6foR7KZ2nOelbNIaqW5Sd38q75tGRXqQl9MUmwleCXGzbja1nd+lJLVeCQ4FI2ypBdfr/+LaypaaJMhKGp7S0lJfluZGQI5bL//FocDd1KB1b1YbNbFSn/aYp2iMjdPFsye1YkCcde0vQ7I+gFb7ZReiP202TRzDffYhLSCB5we2xvcG1UM805NAXP2lzTTW6Z84mdHvQ9BktQjybsNBudgGXuX+tZtJ5mjHwNlcWGyiWwYpu8IWWuNWzZ5AOhyei5giqK62lYHY3Ymw8AAtD2eOMicnNE/tV12vbVYLNnbo2u0W/+4E/ZKSkT3fMontPtAHTt33ZvdTO3X0QSwWcHvIvouNU9nLCTir7H3B4Fn7BVJagw9f2XMfangEw0KeeK8trX7LzhUNZyS+ZwdE8fMQnBZVCAPiGkF/UEOlyYSrL/k0sno86JC4SMnH1zguc0aIPPlXONBSUVbHPV2tErWnHtwKxfcXwfxSykPyh1sq2J8W0ITHoGyzL89mYVBSSNJhV9844XUpy7xsX1DikY32EDG7eY2FplBre4TIU9/L7hPDNbi6lS0RfgbFXxSwmATlTtWSB1QwgLVTIg5v+RWy9TGIWlPugU0naqB+3VfU9Htk8xb+EkeVtAHQ+COPlZPdmXUSVXQE2Ad6OUIIoT6xtLXi9RGJV4bXEatN6eOEcqP8vggy0aBuLEpwrPR1eUisDSi3uEMjK+BLRbAe3xGcAtso6tr/trr5SO+98JWrUnQbqOc4sIIiruZ6KQr8WKas2Z4hkvZozKmzoChgdSOeJHxhO/h8SO0HikxEgrB905+WCE9l6GC0s4kq5F0wLnRyGGS6M2WdE5FUL/aKWRHEkoH4JsfQ+Jj2mXv2NcFUHbD2Y0r48s850J0MTJRtDUfvvNkQk2weh/ayHwvq7xnVNQGk+W444RJlYnxr++g60BnexzhgaOPpp2QjsaEWeEDSgexhEaZmnT9NIXTF4eJxY3qQRRR4XDa61Y80akq/rJArRaw3XCrEzppC9tApjnz67eEUsrlZoqQ9kKj1KVy9nfFlaLgVVf9QeBxc3F809cp9eWjZr1JvF+D1Q0wVj5lRDQTpjCeGXmbUn9YfuIXXdLNONdDPvjyyH58YEtxp7dbzSELvjbukmB13iqFuGnKSxzhpB8c6qBf/UlXKCDCE1gVJiDzFeODks37Q5IR3mBRaTBHbspnR2hXIkkyAxcC7SW91q6SRbLThk9/mpN9Shzb6Wrne39RxkzEt2UwIWvFR/hF+NF+sXsHqHebfZtSIbHD++rPwD/k9P9/Ye73eyNq0uz+nI9ZG8q8WhplvBkW6Yks=