---
kind: pipeline
type: exec
name: Build all hosts

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: Show flake info
  commands:
  - nix --experimental-features "nix-command flakes" flake show
  - nix --experimental-features "nix-command flakes" flake metadata
  - nix --experimental-features "nix-command flakes" flake check

- name: Run flake checks
  commands:
  - nix --experimental-features "nix-command flakes" flake check --show-trace

- name: Build aida
  commands:
  - nix build -v '.#nixosConfigurations.aida.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"

- name: Build kora
  commands:
  - nix build -v '.#nixosConfigurations.kora.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"

- name: Build quinjet
  commands:
  - nix build -v '.#nixosConfigurations.quinjet.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"

- name: Build the-hub
  commands:
  - nix build -v '.#nixosConfigurations.the-hub.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"

- name: Build the-bus
  commands:
  - nix build -v '.#nixosConfigurations.the-bus.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"

- name: Build water-on-fire
  commands:
  - nix build -v '.#nixosConfigurations.water-on-fire.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"

trigger:
  branch:
  - main
  event:
  - push
  - pull_request
  - cron

---
kind: pipeline
type: exec
name: build flake update & push into update-flake

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: flake update
  commands:
  - nix --experimental-features "nix-command flakes" flake update --inputs-from nixpkgs
  
- name: Show git diff
  commands:
  - git diff

- name: Show flake info
  commands:
  - nix --experimental-features "nix-command flakes" flake show
  - nix --experimental-features "nix-command flakes" flake metadata
  - nix --experimental-features "nix-command flakes" flake check

- name: Run flake checks
  commands:
  - nix --experimental-features "nix-command flakes" flake check --show-trace

- name: Build aida
  commands:
  - nix build -v '.#nixosConfigurations.aida.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"

- name: Build kora
  commands:
  - nix build -v '.#nixosConfigurations.kora.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"

- name: Build quinjet
  commands:
  - nix build -v '.#nixosConfigurations.quinjet.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"

- name: Build the-hub
  commands:
  - nix build -v '.#nixosConfigurations.the-hub.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"

- name: Build the-bus
  commands:
  - nix build -v '.#nixosConfigurations.the-bus.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"

- name: Build water-on-fire
  commands:
  - nix build -v '.#nixosConfigurations.water-on-fire.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"

- name: push updated flake
  environment:
    SSH_KEY:
      from_secret: id_rsa
  commands:
  - mkdir ~/.ssh
  - echo $SSH_KEY >> ~/.ssh/id_rsa
  - chmod 400 ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
  - ssh-keyscan github.com >> ~/.ssh/known_hosts
  - git config --global user.name "MayNiklas"
  - git config --global user.email info@niklas-steffen.de
  - git remote set-url origin git@github.com:MayNiklas/nixos.git
  - git checkout -B update-flake
  - git add flake.lock
  - git commit -m "❄️ Update flake.lock"
  - git push --set-upstream origin update-flake --force

trigger:
  branch:
  - main
  - optimize-droneci
  event:
  - push
  - cron

---
kind: secret
name: id_rsa
data: bD3D9/vyV/LCf4Nsd22vNpDTltT05h4yEEIDiifzXiDpD649ORI/1xsenjPePhbW34BFD7AYQUrh7MwyWGJUyyiTnlFVx+dFlVwD+9AalIn48iAbSPbGGp8S0RF4V14icPDKwXCprVXmt+ZyrgAWT3DpQ366dsNl+OMGtIW08Qey+UIna+cluybLlFRJaWghZ4XH+ZhemppYFdvGRglU2wDHaOVvf6VJqyRL+3sP2f1skaualHBwBqGjTQuO+ViX8WAELHuR2+U59m/pm74XIjvdbhHhT1g/WVYXSmngznCl+dqHTTsge+eembGa/AYGyLuOJjU33joxh/qMPCqd4YZRb+FRzYqTEJ7spmlnLWHS6a71jg4PBH6TyBhsQosLAoIoEV0yDzc4rjO4eOCeOVpd1kQPz9TqtNXCDZibAHEVNX+I+R9IQoXA+bOVfRVEZZO2LFDLniDqOOyy0vVPbeefyTz7yP7FOdBXVKBvrB517kHXL1gD25NPkC12KJt5k9xBW7S7j1AFpfKJTQY7gzJBdZm6YuysikLF7Wx4dqOsHuEEA5O8IVb5Gv6vVwkwtmkJi839ffg/yr7da8hGiJaU9/T/xHzsMmcku5h1/vYWbAclE2enmxXb6LqsPZsJze4AQvElqQctp8DzFuKh9bXrW++rSikzNP8TKTtckLV58kup+4EInTpSR5ACSw4k1wXuwaIDb+P+QmuUkXM4chwP1Hz6sE2TXjn3/pyz0B10+wXyrE6ytMk0d+SwvnD5KQv3+PT0EfptQjApyJ4vPVi5S7ByW6Za4zlx83WeTUuZNl28Tr3NnWcoKTsqM/ffT/ei4YU6RTgfertgkytf2exZdhmZAZao9cA4OGgKdzXK80SaxEWrgMwv31MNSgmP4LhMkaBebc5T4+s39jIcZdJAVrliNy+aPRxqi+aEG1a63HvZp1qtiqdJRJWhJdMPQQ73QVzPkqnr+OYKDubUsi9r7gK80Uac2du43G+hmVMUqy2p0TV3sggWcUaCXGzLeYaR1ZQJ3D+1Vh8+F6oNISqKbNCVBkcDv+h0oKa9UIZ+O4uZQqG2p/2DelAhGy9JCFmTVwjXw1LaUIXcflbYlSjpxh/BRVSGTW8bdL6yGh1FyrmGoDTgwjiypU3cwW1BRaHzzA5X7ejChhTKBMOEVWzwzQe7XGXPztOCEYxhtYt/iXGIKMkjNvkH+Grq4vliQhxNAn7cWf/OU79ILC3XCl9bans/Mj/ctmVVOOQjhE0ljTguoTDoyH4wi7mrvfBeJ7ldebE7HuNF2hVdL3f1U1e/W0dIIpXm+miu/GC+Yot1Rr4lzug8G5ZhjFkX8bb3G962aD9zCT33EMsCppppFnWacZ5ASA6er2T5WBn/8RCBb8lFrJzApZECIvrendN45UebNbhrbomlrKffpfxvsp1hF1XinD3uvrJlPz5YxYpXaMGEAHrjUoSaS4TNXxtfyBHcWKJ8fOGHidywvwnjxRCy/TyD+3t3O+Hiy/YzZ4BJ1j5tGOPUinc1foYCvAIxR68VagO7q5ccyrMcwDSVAcchXBk/2uTnVL6szHlFkQLBW3Ds5rEtUShhmgo0UwGUS3PbgBPPnUZJwa4syVsF0hNUvtJJHUJm44C8idSGTcaVfpamLUlZj8XCvg6xblE78eoZbxN8in5uil/T3KFjF6/+wswsrnFXfAYqSRcw6SAnR9ZsPkfLhC1su2gZf9HbpHZIRgz6sW9FjuR6EQf3h67djB2D0lfTBDBzwq4rxrQggsVQio4eoROYVCw7JV6VFdqZrwk3ogoPlEI93qhb57YBoGBTdG7Cle7qgTshItPL9h3xz6Ox+ZVo8zm36k+kMCLDCdrfKgj257n5kGxr2VUN5A47T2t/xU3zIshRjVBYsOogdn2I6Og5jJ5CWfLpvE3UDc2cVMt5ZnsvXWnXMHkEPV4oLoi3H5221UXg4Zi8dStt64YrPI/ja0PgxdKaYbZqTw5oyTj2oRY9Eri1aXxTQl0Qf6w208wNL7k5yItP//2P0ksaZTdPLuapeYcvM1CGP4gJz4RR/eb01gBEEAxO1O6VPhDWaA5fHlxYIiT2Gtv5zaHFNw/hVu3V3hDW40RotajJi/OkktMv5ZleDP+X4UPTly92REDsT+KnKdu2rP+v4vfngJ8F6gfR0UO9E3aTop1On//U8RZwv9eSw7njgmnvrzEB8MA7CRHTnc75nQgJjKfcPMrWY4PIrKDswWtD6/iuVLdNwQuvsL+jqG5VSJg/PPzpxV6GMLvt7//vDS1hwQ/R/qhfgC8AJ6Y1pfYxDNbsIm5CKzEM9JmClcvK8M7IK9BoYSLxjz+KCH7Wc3qViHwTKMOauRHi5zUAfCuD2iDYtSWapWcLMpOOWEe9UtxA4dfSpm/N4tALWejliqS4WvscV44vrwWy+5BS+HyGtVhhTHJfKHxfQ5Mm4yCU17Yz8wadhvMUloJNQp7GjaGPc59qDm94w9Dd1sqxLWIfKRpzCyyysekGDiWjqOPuGPhoIIJyVeF9Fcnn+9/FmR4PoHDQfJsq0JSUosT5YbUGqpMacZ7tjXUOD7d2XzAmBJ2JoDPNnHoclWL1Kssu6tUuLnt5ftcLGbSVfdBG0mbjfMXhfDBd6lbKkO1ja3hSEMjBtMpQdVEnLgN/hoXuioEZQ9d7e5zTHSXKk4Q4kP65OWeSunNUYaEYMwDJYlu49JWxpcqK+ICzfZTACV5x/rmkJXq2m8lTzuxZjd52M2PhQiNP/3sqoj4jnaY7kSha3gjlhB3vGrxR3aPkbdPFBcop/k5x+e6nrm+CV7MpuIb/q9S43crrJWd1o/Tlix5PWYAaARiG34LgYrXqUmOJgwIwnGit5eZxxJRgiIn0u4ZqFkokTg3V3EKcxDlKSwK57HOiw+wNUkUViL8bjnja4yLpFCb3mfWwFNClMVJD8V0D4Z5z2avYhUcBzfMCey2ccQFKvb9yi9+7Zy4F79ig7AP5GqVLnnC7CiaxXOC/0rAWzAtlRPX6bQPBv0vGM9avSdfAFeZdxCiTBU9IGoutnK5+8ZocfZakFfxsSpC+8ybKSPCzMrHQ4I0tY7cHlmaFu2ZxqiAEuadGD+slQuk29jI9Gn6y3uvRu3pvk3p1hRKrzcYOfAPHMJu7F+glBBdmUWphQragkWwt26NuXDNT+TkiHSVcfT5TiYIfoT2tjzppachzslLKmqgxlzzrSiFRJF7RvcEOAr4UscA3TARqwM7sBviV9t0vsQnSJgQ6ViAZiyck6iZFdzjetmItI25pvxCupdFHVk0HcfKOuF3pUSyGEv4L
