# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  nixos-hardware,
  ...
}:
let
  primaryDisk = "/dev/nvme0n1";
  GiB = 1024 * 1024 * 1024;
in
{

  imports = [ ];

  services.fwupd.enable = true;

  disko.devices = {
    disk = {
      main = {
        type = "disk";
        device = primaryDisk;
        content = {
          type = "gpt";
          partitions = {
            boot = {
              size = "1M";
              type = "EF02";
            };
            ESP = {
              size = "512M";
              type = "EF00";
              content = {
                type = "filesystem";
                format = "vfat";
                mountpoint = "/boot";
                mountOptions = [ "umask=0077" ];
              };
            };
            swap = {
              size = "48G";
              content = {
                type = "swap";
              };
            };
            zfs = {
              size = "100%";
              content = {
                type = "zfs";
                pool = "zroot";
              };
            };
          };
        };
      };
    };
    zpool = {
      zroot = {
        type = "zpool";
        options.cachefile = "none";
        rootFsOptions = {
          compression = "zstd";
          acltype = "posixacl";
          xattr = "sa";
          atime = "off";
          "com.sun:auto-snapshot" = "false";
        };
        postCreateHook = "zfs list -t snapshot -H -o name | grep -E '^zroot@blank$' || zfs snapshot zroot@blank";

        datasets = {
          root = {
            type = "zfs_fs";
            mountpoint = "/";
            options.mountpoint = "legacy";
          };
          home = {
            type = "zfs_fs";
            mountpoint = "/home";
            options.mountpoint = "legacy";
            options."com.sun:auto-snapshot" = "true";
          };
          nix = {
            type = "zfs_fs";
            mountpoint = "/nix";
            options.mountpoint = "legacy";
          };
        };
      };
    };
  };

  services.zfs.trim.enable = true;
  services.zfs.autoScrub.enable = true;

  # cat /sys/module/zfs/parameters/zfs_arc_max
  boot.extraModprobeConfig = ''
    options zfs zfs_arc_max=${toString (2 * GiB)}
  '';

  boot.binfmt.emulatedSystems = [ "aarch64-linux" ];
  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "sdhci_pci"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.kernelPackages = pkgs.linuxPackages;
  boot.supportedFilesystems = [ "zfs" ];
  boot.extraModulePackages = [ ];

  # Bootloader
  boot.loader = {
    grub = {
      devices = [ primaryDisk ];
      efiSupport = true;
      efiInstallAsRemovable = true;
    };
    timeout = 10;
  };

  swapDevices = [ ];

  boot.zfs.allowHibernation = true;
  boot.zfs.forceImportRoot = false;
  boot.resumeDevice = "/dev/nvme0n1p3";

  networking.hostId = "f9cad67b";
  networking.modemmanager.enable = true;
  networking.modemmanager.fccUnlockScripts = [
    {
      id = "2cb7:0210";
      path = "${pkgs.modemmanager}/share/ModemManager/fcc-unlock.available.d/2c7c";
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  services.throttled.enable = lib.mkDefault true;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.enableRedistributableFirmware = config.nixpkgs.config.allowUnfree;
}
