{
  "labels": {
    "backend": "local",
    "platform": "linux/arm64"
  },
  "steps": [
    {
      "commands": [
        "nix flake show"
      ],
      "image": "bash",
      "name": "Nix flake show"
    },
    {
      "commands": [
        "attic login lounge-rocks https://cache.lounge.rocks $ATTIC_KEY --set-default"
      ],
      "environment": {
        "ATTIC_KEY": {
          "from_secret": "attic_key"
        }
      },
      "image": "bash",
      "name": "Setup Attic"
    },
    {
      "commands": [
        "nix-fast-build --no-nom --skip-cached --attic-cache lounge-rocks:nix-cache --flake \".#checks.$(nix eval --raw --impure --file builtins.currentSystem)\""
      ],
      "failure": "ignore",
      "image": "bash",
      "name": "Build all outputs for this architecture"
    },
    {
      "commands": [
        "nix-fast-build --no-nom --skip-cached --flake \".#checks.$(nix eval --raw --impure --file builtins.currentSystem)\""
      ],
      "image": "bash",
      "name": "Verify all builds succeeded"
    }
  ],
  "when": [
    {
      "event": "manual"
    },
    {
      "branch": "main",
      "event": "push"
    },
    {
      "branch": "update_flake_lock_action",
      "event": "push"
    }
  ]
}
