labels:
  backend: local
  platform: linux/amd64

when:
  event: manual

steps:
  - name: Setup Attic
    image: bash
    commands:
      - attic login lounge-rocks https://cache.lounge.rocks $ATTIC_KEY --set-default
    secrets:
      - attic_key

  - name: build flake preview diff
    image: bash
    commands:
      - nix run 'github:MayNiklas/flake-preview-update' -- aida daisy deke kora simmons snowflake the-bus the-hub

  - name: output total flake diff
    image: bash
    commands:
      - cat diff_lists/diff_list.txt

  - name: output diff aida
    image: bash
    commands:
      - cat diff_lists/aida.txt

  - name: output diff daisy
    image: bash
    commands:
      - cat diff_lists/daisy.txt

  - name: output diff deke
    image: bash
    commands:
      - cat diff_lists/deke.txt

  - name: output diff kora
    image: bash
    commands:
      - cat diff_lists/kora.txt

  - name: output diff simmons
    image: bash
    commands:
      - cat diff_lists/simmons.txt

  - name: output diff snowflake
    image: bash
    commands:
      - cat diff_lists/snowflake.txt

  - name: output diff the-bus
    image: bash
    commands:
      - cat diff_lists/the-bus.txt

  - name: output diff the-hub
    image: bash
    commands:
      - cat diff_lists/the-hub.txt

  - name: push all hosts to Attic
    image: bash
    commands:
      - attic push lounge-rocks:nix-cache result*
