labels:
  backend: local
  platform: linux/amd64

when:
  event: manual

steps:
  - name: Setup Attic
    image: bash
    commands:
      - attic login lounge-rocks https://cache.lounge.rocks $ATTIC_KEY --set-default
    secrets:
      - attic_key

  - name: build flake preview diff
    image: bash
    commands:
      - nix run 'github:MayNiklas/flake-preview-update' -- aida daisy deke kora kora simmons snowflake the-bus the-hub

  - name: output flake preview diff
    image: bash
    commands:
      - cat diff_list.txt

  - name: push all hosts to Attic
    image: bash
    commands:
      - attic push lounge-rocks:nix-cache result*
