{
  "labels": {
    "backend": "local",
    "platform": "linux/amd64"
  },
  "steps": [
    {
      "commands": [
        "nix flake show"
      ],
      "image": "bash",
      "name": "Nix flake show"
    },
    {
      "commands": [
        "nix flake check"
      ],
      "image": "bash",
      "name": "Nix flake check"
    },
    {
      "commands": [
        "attic login lounge-rocks https://cache.lounge.rocks $ATTIC_KEY --set-default"
      ],
      "image": "bash",
      "name": "Setup Attic",
      "secrets": [
        "attic_key"
      ]
    },
    {
      "commands": [
        "nix build --print-out-paths '.#nixosConfigurations.aida.config.system.build.toplevel' -o 'result-aida'"
      ],
      "image": "bash",
      "name": "Build aida"
    },
    {
      "commands": [
        "nix path-info --closure-size -h $(readlink -f 'result-aida')"
      ],
      "image": "bash",
      "name": "Show aida info"
    },
    {
      "commands": [
        "attic push lounge-rocks:nix-cache 'result-aida'"
      ],
      "image": "bash",
      "name": "Push aida to Attic"
    },
    {
      "commands": [
        "nix build --print-out-paths '.#nixosConfigurations.daisy.config.system.build.toplevel' -o 'result-daisy'"
      ],
      "image": "bash",
      "name": "Build daisy"
    },
    {
      "commands": [
        "nix path-info --closure-size -h $(readlink -f 'result-daisy')"
      ],
      "image": "bash",
      "name": "Show daisy info"
    },
    {
      "commands": [
        "attic push lounge-rocks:nix-cache 'result-daisy'"
      ],
      "image": "bash",
      "name": "Push daisy to Attic"
    },
    {
      "commands": [
        "nix build --print-out-paths '.#nixosConfigurations.deke.config.system.build.toplevel' -o 'result-deke'"
      ],
      "image": "bash",
      "name": "Build deke"
    },
    {
      "commands": [
        "nix path-info --closure-size -h $(readlink -f 'result-deke')"
      ],
      "image": "bash",
      "name": "Show deke info"
    },
    {
      "commands": [
        "attic push lounge-rocks:nix-cache 'result-deke'"
      ],
      "image": "bash",
      "name": "Push deke to Attic"
    },
    {
      "commands": [
        "nix build --print-out-paths '.#nixosConfigurations.kora.config.system.build.toplevel' -o 'result-kora'"
      ],
      "image": "bash",
      "name": "Build kora"
    },
    {
      "commands": [
        "nix path-info --closure-size -h $(readlink -f 'result-kora')"
      ],
      "image": "bash",
      "name": "Show kora info"
    },
    {
      "commands": [
        "attic push lounge-rocks:nix-cache 'result-kora'"
      ],
      "image": "bash",
      "name": "Push kora to Attic"
    },
    {
      "commands": [
        "nix build --print-out-paths '.#nixosConfigurations.simmons.config.system.build.toplevel' -o 'result-simmons'"
      ],
      "image": "bash",
      "name": "Build simmons"
    },
    {
      "commands": [
        "nix path-info --closure-size -h $(readlink -f 'result-simmons')"
      ],
      "image": "bash",
      "name": "Show simmons info"
    },
    {
      "commands": [
        "attic push lounge-rocks:nix-cache 'result-simmons'"
      ],
      "image": "bash",
      "name": "Push simmons to Attic"
    },
    {
      "commands": [
        "nix build --print-out-paths '.#nixosConfigurations.snowflake.config.system.build.toplevel' -o 'result-snowflake'"
      ],
      "image": "bash",
      "name": "Build snowflake"
    },
    {
      "commands": [
        "nix path-info --closure-size -h $(readlink -f 'result-snowflake')"
      ],
      "image": "bash",
      "name": "Show snowflake info"
    },
    {
      "commands": [
        "attic push lounge-rocks:nix-cache 'result-snowflake'"
      ],
      "image": "bash",
      "name": "Push snowflake to Attic"
    },
    {
      "commands": [
        "nix build --print-out-paths '.#nixosConfigurations.the-bus.config.system.build.toplevel' -o 'result-the-bus'"
      ],
      "image": "bash",
      "name": "Build the-bus"
    },
    {
      "commands": [
        "nix path-info --closure-size -h $(readlink -f 'result-the-bus')"
      ],
      "image": "bash",
      "name": "Show the-bus info"
    },
    {
      "commands": [
        "attic push lounge-rocks:nix-cache 'result-the-bus'"
      ],
      "image": "bash",
      "name": "Push the-bus to Attic"
    },
    {
      "commands": [
        "nix build --print-out-paths '.#nixosConfigurations.the-hub.config.system.build.toplevel' -o 'result-the-hub'"
      ],
      "image": "bash",
      "name": "Build the-hub"
    },
    {
      "commands": [
        "nix path-info --closure-size -h $(readlink -f 'result-the-hub')"
      ],
      "image": "bash",
      "name": "Show the-hub info"
    },
    {
      "commands": [
        "attic push lounge-rocks:nix-cache 'result-the-hub'"
      ],
      "image": "bash",
      "name": "Push the-hub to Attic"
    }
  ],
  "when": [
    {
      "branch": "main",
      "event": "push"
    },
    {
      "branch": "update_flake_lock_action",
      "event": "push"
    }
  ]
}
