{
  "labels": {
    "backend": "local",
    "platform": "linux/amd64"
  },
  "steps": [
    {
      "commands": [
        "nix flake show"
      ],
      "image": "bash",
      "name": "Nix flake show"
    },
    {
      "commands": [
        "attic login lounge-rocks https://cache.lounge.rocks $ATTIC_KEY --set-default"
      ],
      "environment": {
        "ATTIC_KEY": {
          "from_secret": "attic_key"
        }
      },
      "image": "bash",
      "name": "Setup Attic"
    },
    {
      "commands": [
        "nix-fast-build --no-nom --skip-cached --attic-cache lounge-rocks:nix-cache --flake \".#checks.$(nix eval --raw --impure --file builtins.currentSystem)\""
      ],
      "failure": "ignore",
      "image": "bash",
      "name": "Build all outputs for this architecture"
    },
    {
      "commands": [
        "nix build --print-out-paths '.#nixosConfigurations.aida.config.system.build.toplevel'"
      ],
      "failure": "ignore",
      "image": "bash",
      "name": "Rebuild aida (diagnostic)",
      "when": {
        "status": "failure"
      }
    },
    {
      "commands": [
        "nix path-info --closure-size -h $(readlink -f 'result-$(nix eval --raw --impure --file builtins.currentSystem).aida')"
      ],
      "failure": "ignore",
      "image": "bash",
      "name": "Show aida info"
    },
    {
      "commands": [
        "nix build --print-out-paths '.#nixosConfigurations.daisy.config.system.build.toplevel'"
      ],
      "failure": "ignore",
      "image": "bash",
      "name": "Rebuild daisy (diagnostic)",
      "when": {
        "status": "failure"
      }
    },
    {
      "commands": [
        "nix path-info --closure-size -h $(readlink -f 'result-$(nix eval --raw --impure --file builtins.currentSystem).daisy')"
      ],
      "failure": "ignore",
      "image": "bash",
      "name": "Show daisy info"
    },
    {
      "commands": [
        "nix build --print-out-paths '.#nixosConfigurations.deke.config.system.build.toplevel'"
      ],
      "failure": "ignore",
      "image": "bash",
      "name": "Rebuild deke (diagnostic)",
      "when": {
        "status": "failure"
      }
    },
    {
      "commands": [
        "nix path-info --closure-size -h $(readlink -f 'result-$(nix eval --raw --impure --file builtins.currentSystem).deke')"
      ],
      "failure": "ignore",
      "image": "bash",
      "name": "Show deke info"
    },
    {
      "commands": [
        "nix build --print-out-paths '.#nixosConfigurations.fitz.config.system.build.toplevel'"
      ],
      "failure": "ignore",
      "image": "bash",
      "name": "Rebuild fitz (diagnostic)",
      "when": {
        "status": "failure"
      }
    },
    {
      "commands": [
        "nix path-info --closure-size -h $(readlink -f 'result-$(nix eval --raw --impure --file builtins.currentSystem).fitz')"
      ],
      "failure": "ignore",
      "image": "bash",
      "name": "Show fitz info"
    },
    {
      "commands": [
        "nix build --print-out-paths '.#nixosConfigurations.kora.config.system.build.toplevel'"
      ],
      "failure": "ignore",
      "image": "bash",
      "name": "Rebuild kora (diagnostic)",
      "when": {
        "status": "failure"
      }
    },
    {
      "commands": [
        "nix path-info --closure-size -h $(readlink -f 'result-$(nix eval --raw --impure --file builtins.currentSystem).kora')"
      ],
      "failure": "ignore",
      "image": "bash",
      "name": "Show kora info"
    },
    {
      "commands": [
        "nix build --print-out-paths '.#nixosConfigurations.simmons.config.system.build.toplevel'"
      ],
      "failure": "ignore",
      "image": "bash",
      "name": "Rebuild simmons (diagnostic)",
      "when": {
        "status": "failure"
      }
    },
    {
      "commands": [
        "nix path-info --closure-size -h $(readlink -f 'result-$(nix eval --raw --impure --file builtins.currentSystem).simmons')"
      ],
      "failure": "ignore",
      "image": "bash",
      "name": "Show simmons info"
    },
    {
      "commands": [
        "nix build --print-out-paths '.#nixosConfigurations.snowflake.config.system.build.toplevel'"
      ],
      "failure": "ignore",
      "image": "bash",
      "name": "Rebuild snowflake (diagnostic)",
      "when": {
        "status": "failure"
      }
    },
    {
      "commands": [
        "nix path-info --closure-size -h $(readlink -f 'result-$(nix eval --raw --impure --file builtins.currentSystem).snowflake')"
      ],
      "failure": "ignore",
      "image": "bash",
      "name": "Show snowflake info"
    },
    {
      "commands": [
        "nix build --print-out-paths '.#nixosConfigurations.the-bus.config.system.build.toplevel'"
      ],
      "failure": "ignore",
      "image": "bash",
      "name": "Rebuild the-bus (diagnostic)",
      "when": {
        "status": "failure"
      }
    },
    {
      "commands": [
        "nix path-info --closure-size -h $(readlink -f 'result-$(nix eval --raw --impure --file builtins.currentSystem).the-bus')"
      ],
      "failure": "ignore",
      "image": "bash",
      "name": "Show the-bus info"
    },
    {
      "commands": [
        "nix build --print-out-paths '.#nixosConfigurations.the-hub.config.system.build.toplevel'"
      ],
      "failure": "ignore",
      "image": "bash",
      "name": "Rebuild the-hub (diagnostic)",
      "when": {
        "status": "failure"
      }
    },
    {
      "commands": [
        "nix path-info --closure-size -h $(readlink -f 'result-$(nix eval --raw --impure --file builtins.currentSystem).the-hub')"
      ],
      "failure": "ignore",
      "image": "bash",
      "name": "Show the-hub info"
    },
    {
      "commands": [
        "nix-fast-build --no-nom --skip-cached --flake \".#checks.$(nix eval --raw --impure --file builtins.currentSystem)\""
      ],
      "image": "bash",
      "name": "Verify all builds succeeded",
      "when": {
        "status": "failure"
      }
    }
  ],
  "when": [
    {
      "event": "manual"
    },
    {
      "branch": "main",
      "event": "push"
    },
    {
      "branch": "update_flake_lock_action",
      "event": "push"
    }
  ]
}
