{
  "labels": {
    "backend": "local",
    "platform": "linux/amd64"
  },
  "steps": [
    {
      "commands": [
        "attic login lounge-rocks https://cache.lounge.rocks $ATTIC_KEY --set-default"
      ],
      "environment": {
        "ATTIC_KEY": {
          "from_secret": "attic_key"
        }
      },
      "image": "bash",
      "name": "Setup Attic"
    },
    {
      "commands": [
        "nix-fast-build --no-nom --skip-cached --attic-cache lounge-rocks:nix-cache --flake \".#checks.x86_64-linux\""
      ],
      "failure": "ignore",
      "image": "bash",
      "name": "Build all outputs for this architecture"
    },
    {
      "commands": [
        "nix build --print-out-paths '.#nixosConfigurations.aida.config.system.build.toplevel' -o 'result-aida'"
      ],
      "failure": "ignore",
      "image": "bash",
      "name": "Rebuild aida (diagnostic)",
      "when": {
        "status": "failure"
      }
    },
    {
      "commands": [
        "nix path-info --closure-size -h $(readlink -f 'result-aida')"
      ],
      "failure": "ignore",
      "image": "bash",
      "name": "Show aida info"
    },
    {
      "commands": [
        "nix build --print-out-paths '.#nixosConfigurations.daisy.config.system.build.toplevel' -o 'result-daisy'"
      ],
      "failure": "ignore",
      "image": "bash",
      "name": "Rebuild daisy (diagnostic)",
      "when": {
        "status": "failure"
      }
    },
    {
      "commands": [
        "nix path-info --closure-size -h $(readlink -f 'result-daisy')"
      ],
      "failure": "ignore",
      "image": "bash",
      "name": "Show daisy info"
    },
    {
      "commands": [
        "nix build --print-out-paths '.#nixosConfigurations.deke.config.system.build.toplevel' -o 'result-deke'"
      ],
      "failure": "ignore",
      "image": "bash",
      "name": "Rebuild deke (diagnostic)",
      "when": {
        "status": "failure"
      }
    },
    {
      "commands": [
        "nix path-info --closure-size -h $(readlink -f 'result-deke')"
      ],
      "failure": "ignore",
      "image": "bash",
      "name": "Show deke info"
    },
    {
      "commands": [
        "nix build --print-out-paths '.#nixosConfigurations.kora.config.system.build.toplevel' -o 'result-kora'"
      ],
      "failure": "ignore",
      "image": "bash",
      "name": "Rebuild kora (diagnostic)",
      "when": {
        "status": "failure"
      }
    },
    {
      "commands": [
        "nix path-info --closure-size -h $(readlink -f 'result-kora')"
      ],
      "failure": "ignore",
      "image": "bash",
      "name": "Show kora info"
    },
    {
      "commands": [
        "nix build --print-out-paths '.#nixosConfigurations.simmons.config.system.build.toplevel' -o 'result-simmons'"
      ],
      "failure": "ignore",
      "image": "bash",
      "name": "Rebuild simmons (diagnostic)",
      "when": {
        "status": "failure"
      }
    },
    {
      "commands": [
        "nix path-info --closure-size -h $(readlink -f 'result-simmons')"
      ],
      "failure": "ignore",
      "image": "bash",
      "name": "Show simmons info"
    },
    {
      "commands": [
        "nix build --print-out-paths '.#nixosConfigurations.snowflake.config.system.build.toplevel' -o 'result-snowflake'"
      ],
      "failure": "ignore",
      "image": "bash",
      "name": "Rebuild snowflake (diagnostic)",
      "when": {
        "status": "failure"
      }
    },
    {
      "commands": [
        "nix path-info --closure-size -h $(readlink -f 'result-snowflake')"
      ],
      "failure": "ignore",
      "image": "bash",
      "name": "Show snowflake info"
    },
    {
      "commands": [
        "nix build --print-out-paths '.#nixosConfigurations.the-bus.config.system.build.toplevel' -o 'result-the-bus'"
      ],
      "failure": "ignore",
      "image": "bash",
      "name": "Rebuild the-bus (diagnostic)",
      "when": {
        "status": "failure"
      }
    },
    {
      "commands": [
        "nix path-info --closure-size -h $(readlink -f 'result-the-bus')"
      ],
      "failure": "ignore",
      "image": "bash",
      "name": "Show the-bus info"
    },
    {
      "commands": [
        "nix build --print-out-paths '.#nixosConfigurations.the-hub.config.system.build.toplevel' -o 'result-the-hub'"
      ],
      "failure": "ignore",
      "image": "bash",
      "name": "Rebuild the-hub (diagnostic)",
      "when": {
        "status": "failure"
      }
    },
    {
      "commands": [
        "nix path-info --closure-size -h $(readlink -f 'result-the-hub')"
      ],
      "failure": "ignore",
      "image": "bash",
      "name": "Show the-hub info"
    },
    {
      "commands": [
        "test -e 'result-aida'",
        "test -e 'result-daisy'",
        "test -e 'result-deke'",
        "test -e 'result-kora'",
        "test -e 'result-simmons'",
        "test -e 'result-snowflake'",
        "test -e 'result-the-bus'",
        "test -e 'result-the-hub'",
        "echo 'All builds succeeded.'"
      ],
      "image": "bash",
      "name": "Verify all builds succeeded",
      "when": {
        "status": "failure"
      }
    }
  ],
  "when": [
    {
      "event": "manual"
    },
    {
      "branch": "main",
      "event": "push"
    },
    {
      "branch": "update_flake_lock_action",
      "event": "push"
    }
  ]
}
